version: "2"
services:
  db-container:
    image: busybox
    volumes:
      - db-volume:/var/lib/mysql/
  nginx-container:
    # image: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/public/src
    depends_on:
      - php-container
  php-container:
    build: ./php
    env_file: ./env/.develop
    environment:
      DATABASE_HOST: mysql-container
    depends_on:
      - mysql-container
    volumes:
      - ./src:/var/www/public/src
  mysql-container:
    image: mysql:5.7.19
    env_file: ./env/.develop
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes_from:
      - db-container
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    depends_on:
      - db-container
  phpmyadmin-container:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql-container
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    depends_on:
      - mysql-container
volumes:
  db-volume:
